# Generated by Django 3.2.16 on 2022-12-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basket_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('-created_at',), 'verbose_name': 'корзина товара', 'verbose_name_plural': 'корзины товаров'},
        ),
    ]
