# Generated by Django 3.2.16 on 2022-12-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'корзина товара', 'verbose_name_plural': 'корзины товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
