# Generated by Django 3.2.16 on 2022-12-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221220_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_price_id',
            field=models.CharField(max_length=128, null=True, verbose_name='price id для stripe'),
        ),
    ]
