# Generated by Django 3.2.16 on 2022-12-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=False, verbose_name='подтверждена почта?'),
        ),
        migrations.CreateModel(
            name='VerifyEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.UUIDField(unique=True, verbose_name='уникальный код для создания ссылки подтверждения почты')),
                ('experation_link', models.DateTimeField(verbose_name='срок жизни ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подтверждение почты',
                'verbose_name_plural': 'подтверждения почт',
            },
        ),
    ]
